[package]
name = "arc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
arc-core.workspace = true
arc-proto.workspace = true
chrono.workspace = true
crossterm.workspace = true
futures.workspace = true
prost-types.workspace = true
ratatui.workspace = true
textwrap.workspace = true
tokio.workspace = true

[dev-dependencies]
expect-test.workspace = true

[lints]
workspace = true
