[package]
name = "arc-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-proto = { workspace = true }
base64 = { workspace = true }
crc32fast = { workspace = true }
futures = { workspace = true }
getrandom = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
wiremock = { workspace = true }

[lints]
workspace = true
